#!/bin/sh

SCRIPT=$(readlink -f $0)
SCRIPT_PATH=$(dirname "$SCRIPT")
cd $SCRIPT_PATH

EXTENSION=""
if [ -f ./Dockerfile.$1 ]
then
    IMAGE="$1"
    EXTENSION=".$IMAGE"

    echo "Running image tagged chdkptp$EXTENSION"
    echo "If you wished to run the $IMAGE command in chdkptp, then run $0 -- $@ instead."

    shift
fi

if [ "$1" = "--" ]
then
    shift
fi

if [ -z "$(docker images -q "chdkptp$EXTENSION")" ]
then
    echo "Image chdkptp$EXTENSION does not exist. Run: make $IMAGE"
    exit 1
fi

if ! [ -z "$DISPLAY" ]
then
    # Lots of help from http://wiki.ros.org/docker/Tutorials/GUI
    #
    XSOCK=/tmp/.X11-unix
    XAUTH=/tmp/.docker.xauth
    touch $XAUTH

    xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
fi

LSUSB_LINE=$(lsusb | grep Canon | head -n1)
DEV=$(echo "$LSUSB_LINE" | sed -En 's:Bus ([0-9]+) Device ([0-9]+).*:/dev/bus/usb/\1/\2:p')

if [ -z "$DEV" ]
then
    echo "Could not find camera."
    exit 1
fi

echo "Forwarding $DEV to docker image, based on this from lsusb:"
echo $LSUSB_LINE

exec docker run -i --rm --privileged \
                --volume=$XSOCK:$XSOCK:rw \
                --volume=$XAUTH:$XAUTH:rw \
                --env="XAUTHORITY=${XAUTH}" \
                --env="DISPLAY" \
                --device=$DEV \
            "chdkptp$EXTENSION" \
            $@
